clean:
	rm -rf $(CURDIR)/build
TEST_READING_DEV_ID:
	west build -- -DTEST_READING_DEV_ID_DEF=ON -DTEST_AES_SS_TWR_INITIATOR_DEF=OFF -DTEST_AES_SS_TWR_RESPONDER_DEF=OFF
TEST_AES_SS_TWR_INITIATOR:
	west build -- -DTEST_READING_DEV_ID_DEF=OFF -DTEST_AES_SS_TWR_INITIATOR_DEF=ON -DTEST_AES_SS_TWR_RESPONDER_DEF=OFF
TEST_AES_SS_TWR_RESPONDER:
	west build -- -DTEST_READING_DEV_ID_DEF=OFF -DTEST_AES_SS_TWR_INITIATOR_DEF=OFF -DTEST_AES_SS_TWR_RESPONDER_DEF=ON

